In [18]:
import numpy as np
def Vander_Matrix(x,N):
    if N<=len(x):
        b=[x**(N-1-i) for i in range(N)]
        c=np.column_stack((b))
        return c
    else:
        print("Value of N should be less than or Equal to Length of array")
    
print( Vander_Matrix(np.array([1, 2, 3, 5]),3))

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
